name: Docker CI

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: umamaheswaridevangam/docker-ci-image
      IMAGE_TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - name: Run containerized tests
      run: |
        docker run -d --name test-container -p 8080:8080 $IMAGE_NAME:$IMAGE_TAG
        sleep 5 # give the app time to start
        curl --fail http://localhost:3003 || (docker logs test-container && exit 1)

    - name: Push Docker image to Docker Hub
      run: |
        docker push $IMAGE_NAME:$IMAGE_TAG
